export const root: string;
export const link: string;
export const container: string;
export const imageWrapper: string;
export const image: string;
export const textWrapper: string;
export const title: string;
export const snippet: string;
export const author: string;
