const bundlePath = 'src/nls/cards';
const messages = {
	brainstorming: 'Brainstorming',
	clearObjectives: 'Clear Objectives',
	codeConventions: 'Code Conventions',
	codeReviews: 'Code Reviews',
	collaboration: 'Collaboration',
	communication: 'Communication',
	decisionMakers: 'Decision Makers',
	delegation: 'Delegation',
	designIteration: 'Design Iteration',
	donuts: 'Donuts!',
	feedback: 'Feedback',
	focusedMeeetings: 'Focused Meetings',
	futureProofing: 'Future Proofing',
	hackathon: 'Hackathon',
	integratedTeams: 'Integrated Teams',
	leadership: 'Leadership',
	modernTools: 'Modern Tools',
	openSource: 'Open Source',
	planning: 'Planning',
	prioritization: 'Prioritization',
	recognition: 'Recognition',
	recruiting: 'Recruiting',
	requirements: 'Requirements',
	reusableCode: 'Reusable Code',
	solidArchitecture: 'Solid Architecture',
	testingPlan: 'Testing Plan',
	aTeam: 'The A-Team',
	unitTesting: 'Unit Testing',
	workLifeBalance: 'Work/Life Balance',
	workshops: 'Workshops'
};
export default { bundlePath, messages };
