import * as accordionPane from './accordion-pane.m.css';
import * as button from './button.m.css';
import * as calendar from './calendar.m.css';
import * as checkbox from './checkbox.m.css';
import * as combobox from './combobox.m.css';
import * as dialog from './dialog.m.css';
import * as icon from './icon.m.css';
import * as grid from './grid.m.css';
import * as gridBody from './grid-body.m.css';
import * as gridCell from './grid-cell.m.css';
import * as gridFooter from './grid-footer.m.css';
import * as gridHeader from './grid-header.m.css';
import * as gridPlaceholderRow from './grid-placeholder-row.m.css';
import * as gridRow from './grid-row.m.css';
import * as label from './label.m.css';
import * as listbox from './listbox.m.css';
import * as progress from './progress.m.css';
import * as radio from './radio.m.css';
import * as select from './select.m.css';
import * as slidePane from './slide-pane.m.css';
import * as slider from './slider.m.css';
import * as splitPane from './split-pane.m.css';
import * as tabController from './tab-controller.m.css';
import * as textArea from './text-area.m.css';
import * as textInput from './text-input.m.css';
import * as enhancedTextInput from './enhanced-text-input.m.css';
import * as timePicker from './time-picker.m.css';
import * as titlePane from './title-pane.m.css';
import * as toolbar from './toolbar.m.css';
import * as tooltip from './tooltip.m.css';
declare const _default: {
    '@dojo/widgets/accordion-pane': typeof accordionPane;
    '@dojo/widgets/button': typeof button;
    '@dojo/widgets/calendar': typeof calendar;
    '@dojo/widgets/checkbox': typeof checkbox;
    '@dojo/widgets/combobox': typeof combobox;
    '@dojo/widgets/dialog': typeof dialog;
    '@dojo/widgets/icon': typeof icon;
    '@dojo/widgets/grid': typeof grid;
    '@dojo/widgets/grid-body': typeof gridBody;
    '@dojo/widgets/grid-cell': typeof gridCell;
    '@dojo/widgets/grid-footer': typeof gridFooter;
    '@dojo/widgets/grid-header': typeof gridHeader;
    '@dojo/widgets/grid-placeholder-row': typeof gridPlaceholderRow;
    '@dojo/widgets/grid-row': typeof gridRow;
    '@dojo/widgets/label': typeof label;
    '@dojo/widgets/listbox': typeof listbox;
    '@dojo/widgets/progress': typeof progress;
    '@dojo/widgets/radio': typeof radio;
    '@dojo/widgets/select': typeof select;
    '@dojo/widgets/slide-pane': typeof slidePane;
    '@dojo/widgets/slider': typeof slider;
    '@dojo/widgets/split-pane': typeof splitPane;
    '@dojo/widgets/tab-controller': typeof tabController;
    '@dojo/widgets/text-area': typeof textArea;
    '@dojo/widgets/text-input': typeof textInput;
    '@dojo/widgets/enhanced-text-input': typeof enhancedTextInput;
    '@dojo/widgets/time-picker': typeof timePicker;
    '@dojo/widgets/title-pane': typeof titlePane;
    '@dojo/widgets/toolbar': typeof toolbar;
    '@dojo/widgets/tooltip': typeof tooltip;
};
export default _default;
