export const todoItem: string;
export const loading: string;
export const edit: string;
export const editing: string;
export const view: string;
export const toggle: string;
export const todoLabel: string;
export const completed: string;
export const destroy: string;
