export const todoDetails: string;
export const title: string;
export const backdrop: string;
export const modal: string;
export const close: string;
export const todoDetailsHeader: string;
export const todoDetailsTextArea: string;
export const lastUpdated: string;
export const toggle: string;
