export const root: string;
export const column: string;
export const heading: string;
export const icon: string;
export const label: string;
export const textInput: string;
export const divider: string;
export const dividerLine: string;
export const dividerBadge: string;
