import { registry } from '@dojo/widget-core/d';
import AppFooter from './widgets/appfooter';
import Button from './widgets/button';
import CheckboxInput from './widgets/CheckboxInput';
import DestroyButton from './widgets/DestroyButton';
import FocusableTextInput from './widgets/FocusableTextInput';
import FormattedDate from './widgets/FormattedDate';
import Home from './widgets/Home';
import Label from './widgets/Label';
import MainSection from './widgets/mainsection';
import SearchInput from './widgets/SearchInput';
import ThemeSwitcher from './widgets/ThemeSwitcher';
import Title from './widgets/Title';
import TodoDetails from './widgets/TodoDetails';
import TodoEditInput from './widgets/TodoEditInput';
import TodoFilter from './widgets/TodoFilter';
import TodoFooter from './widgets/TodoFooter';
import TodoItem from './widgets/TodoItem';
import TodoItemList from './widgets/TodoItemList';
import Toggler from './widgets/Toggler';
import ViewChooser from './widgets/ViewChooser';

registry.define('button', Button);
registry.define('checkbox', CheckboxInput);
registry.define('destroy-button', DestroyButton);
registry.define('details', TodoDetails);
registry.define('filters', TodoFilter);
registry.define('focusabletextinput', FocusableTextInput);
registry.define('footer', AppFooter);
registry.define('formatteddate', FormattedDate);
registry.define('home', Home);
registry.define('label', Label);
registry.define('main-section', MainSection);
registry.define('search', SearchInput);
registry.define('theme-switcher', ThemeSwitcher);
registry.define('title', Title);
registry.define('todo-edit', TodoEditInput);
registry.define('todo-footer', TodoFooter);
registry.define('todo-item', TodoItem);
registry.define('todo-list', TodoItemList);
registry.define('toggler', Toggler);
registry.define('view-chooser', ViewChooser);
